# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Campus42' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Campus42

  target 'Campus42-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Campus42Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Campus42-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Campus42-tvOS

  target 'Campus42-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
